name: Autosquash
on:
  check_run:
    types:
      - completed
  pull_request:
    types:
      - closed
      - labeled
  status: {}

jobs:
  autosquash:
    name: Autosquash
    runs-on: ubuntu-18.04
    steps:
      - uses: tibdex/autosquash@v2
        with:
          github_token: ${{ secrets.BOT_GITHUB_KEY }}
